### ISSUE TITLE
Blog and About us styling refactor for Mobile First / dynamic scaling

### ISSUE THREAD

**Issue by jozue06** [jozue06/pastry-punk#54]
The blog page and about us page both are not scaling well when in mobile view and also when window size is scaled down. Some media queries (@media) and css styling would probably fix those issues. 

Mostly the text is squashed together and the images get skewed when in alternative views.

**Comment by roselara1** [comment]
Working on it!

**Comment by roselara1** [comment]
Can't see my branch..yet again. Will have to re-do and re-clone tomorrow.
